### ISSUE TITLE
minor issue with space

### ISSUE THREAD

**Issue by cpg** [Jasonette/JASONETTE-Android#1]
i noticed that the space component, when not indicating height, appears to not show up, i.e. has zero pixels. this makes things look a little different from ios.

when adding some height, it does render some space.

I had before liberally used `space` in iOS without height when i needed to separate groups of items or something. For consistency, I would recommend either defaulting to the same as iOS when there is no height (preferably), or change the default in iOS to behave the same.

(i did not try horizontal spacing)

**Comment by cpg** [comment]
Example: https://jasonbase.com/things/oJy

Should look like this (under Jason/iOS), if we go by iOS being the golden reference:
http://dl.dropbox.com/u/364883/Screenshots/nzdy.png
@cpg

**Comment by gliechtenstein** [comment]
Is this the same as https://github.com/Jasonette/JASONETTE-Android/issues/2 ?

**Comment by cpg** [comment]
No, if you go to Jason 1.5 and show that test URL you will see that there is no space in betwen the two One elements (the space should have the background color, given that #2 was not fixed in that version).

However, the fixes recently committed do seem to fix this, making space with no style/height specified actually show up with a sensible amount of space.
