### ISSUE TITLE
Keep crashed

### ISSUE THREAD

**Issue by hakimihamdan88** [Jasonette/JASONETTE-Android#10]
your example instagram for android keep crashed when multiple click on bottom menu

**Comment by gliechtenstein** [comment]
Hi, could you give a bit more info on how I can replicate this? 
For example what device you're using, what I need to do to replicate, etc.
That would be super helpful for debugging. Thanks!

**Comment by gliechtenstein** [comment]
Also, if anyone else is seeing this, please share! I have two devices but am having trouble replicating, so any guidance would be helpful.

**Comment by hakimihamdan88** [comment]
@gliechtenstein i have 2 devices produced same result (crashed). you may try click these two buttons 4-5 times repeatedly. 
![img_2016-12-17 15 51 16](https://cloud.githubusercontent.com/assets/1689992/21285372/541558a2-c471-11e6-914f-6d136f393eca.jpg)

**Comment by gliechtenstein** [comment]
OK, I think this should be fixed with https://github.com/Jasonette/JASONETTE-Android/commit/1f7b702882b3f1e0f9e5e0a50a25f247e408f97e

Could you check? Thanks!

**Comment by gliechtenstein** [comment]
Haven't heard back, and we've been using this feature with no problem for a while now, so closing this.
