### ISSUE TITLE
background image is stretched, not on iOS

### ISSUE THREAD

**Issue by j2l** [Jasonette/JASONETTE-Android#104]
Comparing portrait/landscape [body background url](https://docs.jasonette.com/document/#background) behavior on Android and iOS, we can see Android stretches the image, while iOS respects aspect ratio (crop it).
Not sure it needs a sie or distribution parameter.

**Comment by realitix** [comment]
Hello,
I saw that on Android, background is streched and that looks very ugly. To resolve it, you must provide all aspect ratio and detect screen size. It's better to crop the image.

@gliechtenstein I think it's near this place: https://github.com/Jasonette/JASONETTE-Android/blob/develop/app/src/main/java/com/jasonette/seed/Core/JasonViewActivity.java#L1445

On Glide documentation, they say to use transform : http://bumptech.github.io/glide/doc/transformations.html.

I think it should be something like that:

 ```
RequestOptions options = new RequestOptions();
options.centerCrop(context);

with(JasonViewActivity.this)
    .load(JasonImageComponent.resolve_url(c, JasonViewActivity.this))
    .apply(options)
    .into(new SimpleTarget<GlideDrawable>() {
                                            @Override
                                            public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> glideAnimation) {
                                                sectionLayout.setBackground(resource);
                                            }    
                                        });  
```

I can't test on Iphone but behavior must be the same between both.
I will test it when my dev environment will be up. Currently, I'm testing with the Jason APP, so smooth!

**Comment by j2l** [comment]
@realitix Merci !
je le ferme.

**Comment by realitix** [comment]
Why @j2l ? It's not fixed. Can you reopen it ?

**Comment by j2l** [comment]
Si tu veux JS. On verra.

**Comment by realitix** [comment]
Merci @j2l, comment sais-tu que je parle Français ? 

@gliechtenstein My example can't work because it's with Glide 4 and currently, the project uses Glide3.
I let you know when it's done. My dev-env is ready.

**Comment by j2l** [comment]
Because your first name is Jean-Sébastien and you live in Paris :)
It was just a guess.

**Comment by realitix** [comment]
Pas bête !

**Comment by gliechtenstein** [comment]
Thanks to @realitix this has been resolved!! https://github.com/Jasonette/JASONETTE-Android/pull/119#issuecomment-312914111
