### ISSUE TITLE
libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)

### ISSUE THREAD

**Issue by j2l** [Jasonette/JASONETTE-Android#108]
I got `libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)` error in Android Monitor on an empty html web container like:
```jason
{
  "$jason": {
    "head": {
      "title": "Empty Web Container"
    },
    "body": {
      "style": {
        "background": {
          "type": "html",
          "text": "<html></html>",
          "action": {
            "type": "$default"
          }
        }
      }
    }
  }
}
```
A [solution on stackexchange](https://stackoverflow.com/questions/40141194/egl-bad-display-in-android-whilst-debugging-webview), might be applied.
I tried and failed because Jasonette uses WebView getSettings(), not present in WebChromeView.

**Comment by gliechtenstein** [comment]
Hmm does this happen only when the html is empty? Or any other cases?

**Comment by j2l** [comment]
I originally tested a socket.io demo code and got the error, so I emptied html and tried, same error.

**Comment by gliechtenstein** [comment]
I just tried the same code and they all work. I feel like this may be a hardware issue. Could you try:

1. Pulling from the latest develop branch : https://github.com/Jasonette/JASONETTE-Android.git
2. Try the same thing on an emulator?

In my case I can't replicate this on any of the emulators and my devices. If you still get errors, it would be helpful if you can share a screenshot and more info about your device and os version, etc.

**Comment by j2l** [comment]
Ok,  I tried with emulator (API 25), here's the screenshot:
![image](https://user-images.githubusercontent.com/65325/27227200-cb6c30fa-52a2-11e7-8fb7-50ef5d474283.png)
It's not critical but I wonder why.

**Comment by realitix** [comment]
Hello @j2l. Can you take a look at OpenGL support on your computer. It seems to be the problem.

**Comment by j2l** [comment]
Hello @realitix 
I don't understand how opengl on the computer can throw error from mobile.
Can you please explain?

**Comment by j2l** [comment]
Ethan got it.
I double checked with an emulator as he asked, it was on my phone initially.

**Comment by realitix** [comment]
@j2l Apart from errors in log, is the webview working ?
If yes, like @gliechtenstein, it's a hardware issue. What is your phone model ?

**Comment by j2l** [comment]
Didn't you see it appears on an emulator too? Hardware issue? How can be on emulator?
See the upper left corner of my screenshot.

**Comment by realitix** [comment]
Indeed, with API 25, I can see the error

**Comment by j2l** [comment]
I can't continue tracking bugs.

**Comment by paduy** [comment]
I had the same issue when I tried to load webview on Dialog. If I load webview on activity, it works well.
