### ISSUE TITLE
audio record not converting file to m4a

### ISSUE THREAD

**Issue by j2l** [Jasonette/JASONETTE-Android#109]
Example from [documentation](https://docs.jasonette.com/actions/#audiorecord) is not fully working for Android, both on JASON and custom build:
Success is not triggered ($util.alert with {{$jason.url}}).

Reading the source, I can see that the file /recorded_audio.wav get written (line 163 of JasonAudioAction). Audio is recorded, playback is working, and file is written as wav, but no conversion to m4a.
Not sure where/if convert is called. Or should we call $audio.process manually?
Finally, I'm not sure what color option is for, lines 149, 150, 167.

**Comment by gliechtenstein** [comment]
I just tested (both on Jason and the latest version of Jasonette) and it's working fine. 

Could you check again? Maybe you didn't allow permissions as instructed in the documentation? https://docs.jasonette.com/actions/#android-permissions

> Reading the source, I can see that the file /recorded_audio.wav get written (line 163 of JasonAudioAction). Audio is recorded, playback is working, and file is written as wav, but no conversion to m4a.  Not sure where/if convert is called. Or should we call $audio.process manually?


conversion to m4a is done here: https://github.com/Jasonette/JASONETTE-Android/blob/develop/app/src/main/java/com/jasonette/seed/Action/JasonAudioAction.java#L229

which is called by the [process() function](https://github.com/Jasonette/JASONETTE-Android/blob/develop/app/src/main/java/com/jasonette/seed/Action/JasonAudioAction.java#L193), which is called [here](https://github.com/Jasonette/JASONETTE-Android/blob/develop/app/src/main/java/com/jasonette/seed/Action/JasonAudioAction.java#L181).

So you don't need to do anything. It should just work.

> Finally, I'm not sure what color option is for, lines 149, 150, 167.

The color options are the tint color for the audio recorder UI.


Anyway I've checked on all my android devices and they all seem to work. Please try again and let me know.

**Comment by j2l** [comment]
Permissions were allowed, audio is recorded, but not converted.
I don't have a file explorer in the emulator (or I didn't see it).
On my OPO, I gave another try (see date), I get the wav, but no m4a and no success action:
![image](https://user-images.githubusercontent.com/65325/27227638-8bf6ce74-52a4-11e7-9b5f-7445b06ba0dd.png)

Or is it written elsewhere?

In the monitor, it looks like it loads FFMPEG, at RECORD time:
06-16 14:57:51.540 29828-29828/com.test.test D/FFmpeg: Build.CPU_ABI : armeabi-v7a
06-16 14:57:51.544 29828-29828/com.test.test I/FFmpeg: Loading FFmpeg for armv7 CPU

but then, AFTER recording, I get this (may be not related):
06-16 14:57:56.798 29828-29828/com.test.test D/Error: org.json.JSONException: No value for actions

Since I have Firebase and log is Verbose, I also have a lot of info, here's the screenshot:
![image](https://user-images.githubusercontent.com/65325/27228080-7398ce20-52a6-11e7-8c36-ad880ffa46b4.png)


Thanks for the color explanation, I didn't get it. It makes sense :)

**Comment by j2l** [comment]
I can't continue tracking bugs.

**Comment by maks** [comment]
@gliechtenstein while looking to reduce the size of the apk (by removing j2v8 library dependency) I came across this that com.github.adrielcafe:AndroidAudioConverter is infact a wrapper around ffmpeg binary which for arm-eabi is 18MB!
Whats worse though is that its only a arm binary so while not the problem for this issue, it will *never* work on x86 based Android devices. Admittedly they are a small minority, but still there are alot of cheap android x86-based tablet device in the AU market for example, as well as very popular chinese consumer models such as the Xiaomi MiPad 2.
I had a quick search around and it looks like the [android media recorder API supports recording and encoding directly to m4a](https://stackoverflow.com/a/29037489/85472) so perhaps it would be better to use that as it would remove the need for the ffmpeg binary, work on x86 devices and not require separate record and then encode stages?
