### ISSUE TITLE
rotation leads to $show

### ISSUE THREAD

**Issue by cpg** [Jasonette/JASONETTE-Android#11]
it appears that a device rotation leads to `$show` being called, which in one of my cases it leads to a network call and a render.

this is different in Android than iOS, which does not call `$show` on rotation.

however, I am not sure if this is inherent to Android, or an accidental addition or bug.

not a high priority issue.

**Comment by gliechtenstein** [comment]
Fixed with https://github.com/Jasonette/JASONETTE-Android/commit/ff469737fc43c923a4d15055540d0ca1be7931a5
