### ISSUE TITLE
Local image support

### ISSUE THREAD

**Issue by gliechtenstein** [Jasonette/JASONETTE-Android#113]
Feature parity with iOS - https://github.com/Jasonette/JASONETTE-iOS/pull/211

Should support local image rendering for

- header.title
- header.menu
- footer.tabs
- footer.input
- body.style.background
- layers
- sections.items.image
- sections.items.button

**Comment by gliechtenstein** [comment]
Resolved with https://github.com/Jasonette/JASONETTE-Android/commit/87f0f4125aa3413a109998fa1a858279ccf746ba

**Comment by sum12** [comment]
So this support is for images installed with apps.

Any plans to add access to any image(s) on file system?

**Comment by sum12** [comment]
Okay i found https://github.com/Jasonette/JASONETTE-Android/blob/d4a375e0127e6ab4a12883756aa800bfba5005ef/app/src/main/java/com/jasonette/seed/Action/JasonMediaAction.java#L107 but i think its missing a `EXTRA_ALLOW_MULTIPLE` on the intent. So iiuc the image  picker allows picking only one image.

Any way to load multiple images or an entire album?
