### ISSUE TITLE
audio play toggle on android not working

### ISSUE THREAD

**Issue by darenr** [Jasonette/JASONETTE-Android#114]
audio is started with $audio.play, but the toggle effect doesn't work, it won't pause playing audio.

**Comment by gliechtenstein** [comment]
Fixed with https://github.com/Jasonette/JASONETTE-Android/commit/4ab474754cf67b3817af9be6e3b771590495b90b 

Please try out and let me know if it works, and I'll close it.

**Comment by darenr** [comment]
works great thanks.
