### ISSUE TITLE
input text area not responding

### ISSUE THREAD

**Issue by darenr** [Jasonette/JASONETTE-Android#115]
to reproduce:

open:

https://jasonbase.com/things/EYLG.json

the text areas are non responsive to text input

(tested on Android 6 and 7.1)

**Comment by gliechtenstein** [comment]
This is because you have the `$reload` action inside `$load`. This effectively puts everything the load handler into an infinite loop. It should work if you take out the `$load` handler.

**Comment by darenr** [comment]
that was stupid of me, I've just looked and have this error in many places. On iOS it doesn't cause any problems. Thanks for spotting that.

**Comment by gliechtenstein** [comment]
Thanks for pointing out that iOS works fine with this, will need to take a look and make them consistent. Created a ticket for that https://github.com/Jasonette/JASONETTE-iOS/issues/216
