### ISSUE TITLE
footer bar not working properly

### ISSUE THREAD

**Issue by darenr** [Jasonette/JASONETTE-Android#116]
works fine on iOS

http://kadist-ios.herokuapp.com/kmap_main

but on Android (at least on a Blackberry KeyOne) it starts out good, then I click through the tabs left to right then when I get to the last tab (search) and return to the first tab the view doesn't change, at this point it's "confused" and other tabs also don't change the view.

Thanks!

**Comment by gliechtenstein** [comment]
iOS is very forgiving compared to Android in general, which means in most cases when something works on iOS but not on Android, it's more likely that you have made some error which iOS lets pass through while Android doesn't. 

<img width="890" alt="screen shot 2017-06-27 at 10 44 08 am" src="https://user-images.githubusercontent.com/16613330/27593762-030cf64e-5b26-11e7-955a-71dcc812a57d.png">
