### ISSUE TITLE
Add action and href to map component pins

### ISSUE THREAD

**Issue by gliechtenstein** [Jasonette/JASONETTE-Android#144]
currently you can't interact with pins. 

let's add `action` and `href` to each pin

**Comment by maks** [comment]
Great!
I'm happy to implement this. I should have a PR ready on Monday/Tuesday.

**Comment by gliechtenstein** [comment]
@maks yesss looking forward to it!

**Comment by maks** [comment]
PR: #149

**Comment by maks** [comment]
@gliechtenstein this can be closed now that #149 is merged (sorry I forgot to include the "Fixes: XYZ" tag in the original PR comment).
