### ISSUE TITLE
[BUG] $require action not working for local files

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-Android#148]
Remotely hosted views that use the `$require` action work just fine. However, when the same file is used as a local file, it fails.

Test: https://jasonbase.com/things/zM5Q

**Comment by gliechtenstein** [comment]
i thought i understood the problem but got confused after looking at the JSON. It doesn't seem to have any `file://` references. Could you elaborate?

**Comment by drwasho** [comment]
The require action itself doesn't seem to work when this JSON file is used locally.

**Comment by gliechtenstein** [comment]
Should be fixed with https://github.com/Jasonette/JASONETTE-Android/commit/3510018c0c3c517f1789a8765b4c6ed00ad47c2f Please try it out!

**Comment by drwasho** [comment]
Yep, that worked!
