### ISSUE TITLE
READ THIS BEFORE SUBMITTING ISSUE REPORTS

### ISSUE THREAD

**Issue by clsource** [Jasonette/JASONETTE-Android#176]
- **Don't submit issue reports here, they will be closed automatically. Instead submit Jasonette issue reports to the [Jasonette issues repository](https://github.com/Jasonette/Jasonette-issues/issues)**.
- Please do not submit feature requests to the issues repository, instead use the [Jasonette feature requests repository](https://github.com/Jasonette/Jasonette-requests/issues).
- Please do not use the issues repository for Jasonette support, instead use the support forum at [https://forum.jasonette.com/](https://forum.jasonette.com/).
- Always include the Operating System (Android 5.0). Also include the smartphone hardware specs when potentially applicable.
- Indicate any 3rd party frameworks or Apis that are being used when potentially applicable.
- When possible please confirm the issue on the [Jason App](https://docs.jasonette.com/jason/) before submitting an issue report.
- When the issue is resolved, please close it.
- For roadmap and project discussion, please use the [Jasonette repository](https://github.com/Jasonette/Jasonette/issues).

**Comment by maks** [comment]
@clsource per my comment in the iOS repo, this needs discussion.

**Comment by clsource** [comment]
Discussion aproved to ditch this approach 👍
