### ISSUE TITLE
getHttpClient is missing an argument (timeout)

### ISSUE THREAD

**Issue by cpg** [Jasonette/JASONETTE-Android#195]
It appears that compilation of `develop` fails (with latest Android Studio and SDK updates) in this line due to a missing argument in getHttpClient. A `0` may work?

https://github.com/Jasonette/JASONETTE-Android/blob/6213abe0f9677f4eccb9d83a19bab9585bbd9fe7/app/src/main/java/com/jasonette/seed/Service/websocket/JasonWebsocketService.java#L150

**Comment by gliechtenstein** [comment]
Thanks for the report, just fixed it. https://github.com/Jasonette/JASONETTE-Android/commit/8a8740d38d9f503407bc9baf65089169db7156d0
