### ISSUE TITLE
space component does not seem to take background color

### ISSUE THREAD

**Issue by cpg** [Jasonette/JASONETTE-Android#2]
Example: https://jasonbase.com/things/PVq

Should look like this (under Jason/iOS), if we go by iOS being the golden reference:
http://dl.dropbox.com/u/364883/Screenshots/nzdy.png

**Comment by gliechtenstein** [comment]
This should be fixed with https://github.com/Jasonette/JASONETTE-Android/commit/4322730a752184ad25b1dc6b393d8231e5b1ee51

Please check

**Comment by cpg** [comment]
Bug squashed. Great job!
