### ISSUE TITLE
Unable to run the project using latest android studio from a fresh install

### ISSUE THREAD

**Issue by realtebo** [Jasonette/JASONETTE-Android#206]
I fresh installed Android Studio 3 and imported the android project
I got a LOT of grandle warnings and I'm totally unable to make it run.
Please, upgrade the android 'base' project to be usable with more recent Android Studio and sdk versions. 
Or documentation, at minimum, to help use fight the following problems.

```
Error:Failed to find Build Tools revision 25.0.0

Consult IDE log for more details (Help | Show Log)
<a href="install.build.tools">Install Build Tools 25.0.0 and sync project</a>****
```

I installed buidl tools v25

Than I got an invite to update gradle. I clicked on 'never remind'

**Comment by gliechtenstein** [comment]
Hmm, isn't this more of an Android Studio issue?

I think it happens with any other Android project if you don't update build tools https://stackoverflow.com/questions/16619773/failed-to-import-new-gradle-project-failed-to-find-build-tools-revision-0-0

**Comment by realtebo** [comment]
See also #208

**Comment by realtebo** [comment]
Your project is using a lot of outdated dependencies. So, please, try my 2 PR.

**Comment by gliechtenstein** [comment]
merged. Thanks for the PR
