### ISSUE TITLE
error in generating signed apk with progressbar

### ISSUE THREAD

**Issue by cpg** [Jasonette/JASONETTE-Android#210]
```
../app/src/main/java/com/jasonette/seed/Service/agent/JasonAgentService.java
Error:(337) Error: Expected resource of type id [ResourceType]
```

the line is
```
if (agent.findViewById(42) == null) {
```

This does not happen in debug builds.

I have cleaned and rebuilt the project three times.

**Comment by gliechtenstein** [comment]
Fixed with https://github.com/Jasonette/JASONETTE-Android/commit/9da16040de058b7854c2f465109c8613ee214543

Feel free to check and close if that fixed it.
