### ISSUE TITLE
Triggering actions from item not working (works on iOS)

### ISSUE THREAD

**Issue by darenr** [Jasonette/JASONETTE-Android#223]
test case: https://jasonbase.com/things/gzWn

works ok on iOS, I have a per item action which sets a next_page variable then triggers a global action to transition to that jason view.

**Comment by gliechtenstein** [comment]
Fixed with https://github.com/Jasonette/JASONETTE-Android/commit/3591dd69bda112241f63768a7da2ea9c946f1cc0

By the way, both on iOS and Android you don't need to specify `"view": "jason"` if you're just doing jason views. That's the default.
