### ISSUE TITLE
"Jasonette has stopped" crash when using tab navigation

### ISSUE THREAD

**Issue by Chizzoz** [Jasonette/JASONETTE-Android#228]
Hello! I installed Android Studio 3.0.1 with Gradle 4.1 and opened the JASONETTE-Android-master project file. I have been trying the Twitter-UI-example and after I click on the tab navigation links a number of times, I am getting a "Jasonette has stopped" notification and the app crashes. Please assist in helping find out what is wrong with my setup. Below is a screenshot and an error log.

![jasonette has stopped](https://user-images.githubusercontent.com/17289498/37255043-40980de8-254f-11e8-88dd-d2d459c32d59.jpg)

`6472-6472/com.jasonette E/AndroidRuntime: FATAL EXCEPTION: main Process: com.jasonette, PID: 6472
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setSelected(boolean)' on a null object reference
 at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.updateItems(AHBottomNavigation.java:680)
 at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.access$000(AHBottomNavigation.java:52)
 at com.aurelhubert.ahbottomnavigation.AHBottomNavigation$2.onClick(AHBottomNavigation.java:436)
 at android.view.View.performClick(View.java:5637)
 at android.view.View$PerformClick.run(View.java:22429)
 at android.os.Handler.handleCallback(Handler.java:751)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6119)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by gliechtenstein** [comment]
Can you share the exact JSON markup you're trying?

**Comment by Chizzoz** [comment]
Hi! I am using the JSON markup here: https://raw.githubusercontent.com/Jasonette/Twitter/master/home.json

I am now suspecting it's something to do with the current Jasonette build, I experimented by loading the above url in Jason, the JSON browser installed from Play Store and I am getting the same error after clicking tab links a couple of times. I also tested with an older build of Jasonette and this problem is not there.

**Comment by Chizzoz** [comment]
Screenshots:

JSON Browser | Twitter UI Example
---------------- | ------------------
![img_20180313_015335_106](https://user-images.githubusercontent.com/17289498/37315325-c909da72-2661-11e8-81dc-8648b55d30b5.jpg) | ![img_20180313_015309_305](https://user-images.githubusercontent.com/17289498/37315327-c9456d58-2661-11e8-81e4-a07558e647a5.jpg)

**Comment by gliechtenstein** [comment]
I think this was related to a recent upgrade to the library we're using for the tab bar.

I've looked into the issue and think I've fixed it. https://github.com/Jasonette/JASONETTE-Android/commit/98885d0b14ddab39e0378faea4c59e7c84891b76

Please try pulling from the latest develop and retry and let me know if it works. Thanks!

**Comment by Chizzoz** [comment]
Hi! I tried the latest develop, everything seems to work fine, but there is one scenario that seems to be still bringing up the same error. Was trying to put my finger on it and I think it happens when you have html items in the view url that you open.

**Comment by Chizzoz** [comment]
Hi! I tested the latest master branch and this issue is no longer there, it works well. Closing this issue now. Thanks!
