### ISSUE TITLE
$default link click handling for web container didn't work

### ISSUE THREAD

**Issue by arifrifai** [Jasonette/JASONETTE-Android#229]
Jasonette will hang when a link is clicked inside $default type link handling web container.

**Comment by gliechtenstein** [comment]
Can you share a minimal simplest example I can try?

**Comment by arifrifai** [comment]
I test it with the "$default Link Click Handling" demo (the Regular Browser demo), however the selective link click handling is working fine.

**Comment by arifrifai** [comment]
FYI, I test it using the emulator and actual device.

**Comment by gliechtenstein** [comment]
Thanks for reporting, this was a bug that happens on a unique configuration, and the example happened to stumble upon that unique configuration.

It should be fixed now https://github.com/Jasonette/JASONETTE-Android/commit/8cb6abbd7b3aa7d264ea0138c3ca1de6762e89f5

Let me know if it's still broken.

**Comment by arifrifai** [comment]
Thank you, It's working now.
