### ISSUE TITLE
$geo.get not working... "Turn on permissions" error

### ISSUE THREAD

**Issue by nance2uiuc** [Jasonette/JASONETTE-Android#234]
Love the project. However, when I try the $geo.get demo from the jasonpedia app, a screen pops up that says "Turn on permissions. $geo.get requires additional permissions. Got to AndroidManifest.xml file and turn on the permission."

I uncommented the necessary lines, rebuilt the project, and ran. Same error. 

From what I have read, android apps built after Marshmallow need more than just an AndroidManifest.xml addition. Is there a fix for this? My app absolutely needs geolocation.

**Comment by falkogloeckler** [comment]
Same issue here... Did anyone get this running with the Android Emulator?

**Comment by clsource** [comment]
I will see what can I do. This maybe related to this https://developer.android.com/training/permissions/requesting?hl=es-419

**Comment by clsource** [comment]
Fixed in https://github.com/jasonelle/jasonette-android/pull/2
