### ISSUE TITLE
how to really use JSON

### ISSUE THREAD

**Issue by arize99** [Jasonette/JASONETTE-Android#235]
Hello? I can't locate a place to insert my web address and change signatures so that I can upload to play store under my account. I was trying to integrate some native features into my webview app  which was quite frustrating and time consuming. JSON claims I could do this in less than 5 mins. How can I use this? Thanks

**Comment by arize99** [comment]
Also tries to import it to android studio but it returned a gradle error. Something about setting up gradle in HTTP.

**Comment by arize99** [comment]
Tried to import to Android Studio V3 but returned this error

`Could not find method google() for arguments [] on repository container.`

**Comment by lachlanhickey** [comment]
@arize99 This is not a git issue. Post to the forum

**Comment by clsource** [comment]
@arize99 please if you still have problems go to the slack channel at jasonelle.com :) thanks.
