### ISSUE TITLE
jasonbase.com and jasonette.com is down

### ISSUE THREAD

**Issue by NiiVAN** [Jasonette/JASONETTE-Android#239]
It seems Jasonbase and jasonette.com is down as my app suddenly stopped working and i can't log in to view my saved jason data files. Anyone having similar issues at the moment?
![no such app](https://user-images.githubusercontent.com/24251971/44125964-55482710-a02d-11e8-9800-e7bbf83789f3.png)

**Comment by camillerimichael** [comment]
jasonette is up and working.

Jasonbase seems down as well as the forums. I hope @gliechtenstein can shed some light

**Comment by camillerimichael** [comment]
You can close this issue, site is back up!

**Comment by NiiVAN** [comment]
thanks! closed #239
