### ISSUE TITLE
No example of loading.json

### ISSUE THREAD

**Issue by NicksonYap** [Jasonette/JASONETTE-Android#243]
Hi,

Docs mentioned that loading.json came with the project

I've checked Android and iOS github and there is no loading.json

https://docs.jasonette.com/offline/#5-loading-screen

Is there a working example for this?

**Comment by NicksonYap** [comment]
It seems loading.json is no longer used:
https://github.com/Jasonette/JASONETTE-Android/pull/199

EDIT: 
preload is used instead:
https://docs.jasonette.com/href/#preload

Update docs and Medium article?
https://docs.jasonette.com/offline/#5-loading-screen
https://medium.com/@gliechtenstein/jasonette-offline-7d6ed8d58edb



@gliechtenstein

**Comment by clsource** [comment]
thanks for letting me know this!.
