### ISSUE TITLE
Development moved to https://github.com/jasonelle/jasonelle 

### ISSUE THREAD

**Issue by clsource** [Jasonette/JASONETTE-Android#251]
https://github.com/jasonelle/jasonelle
will continue Jasonette legacy. Issues and pull request would be slowly tackled in the other repo

**Comment by carstengrimm** [comment]
Is jasonette discontinued?

**Comment by clsource** [comment]
Here is the history
https://github.com/Jasonette/Jasonette/issues/23

Basically Ethan disappeared. So we are continuing development in a new organization.

**Comment by carstengrimm** [comment]
Thanks for the feedback. 

I was always very happy using jasonette and while development was rather slow i can understand that working on it full time (at least at some point investing alot of time) in open source / free software might not be able to continue forever.

so whatever the future will hold, all the best to ethan

**Comment by moses5407** [comment]
I have to say I'm a little lost in where to participate in the Jasonelle conversation, not being Guthub familiar.

Is this the right place?

First, A HUGE thanks for rescuing this project! I've always been surprised that it hasn't had more traction as an alternative to react/react-native and, well, everything else.

Is there a way to contribute to the process? Like crowd-funding for staff, etc.?

Is Jasonette-web still viable and if so where? And are web mixins data-interactive?
I never saw a presentation about that but it may well have been doable.

FYI, I get a 404 for the reverse-engineered jasonapp. IS that available?
Are you, clsource, available for related contract work?

**Comment by moses5407** [comment]
ok..found the app at this link: https://github.com/jasonelle/docs/tree/develop/examples/jasonette/apps/jason-app

**Comment by moses5407** [comment]
where can we upload and test our jason code?

**Comment by moses5407** [comment]
Just found the blog post about celljs being deprecated ... but I'd love to find someone to hire to avoid this ... assuming mixins can be interactive components.

LMK if this is of interest to anyone with the skills...

**Comment by clsource** [comment]
@moses5407 The alternative to Jasonbase is here https://base.jasonelle.com/ but is recommended that you use a proper server for your apps. Jasonbase is only for testing purposes.

Also the chat is still working http://jasonette.slack.com/ for now is fine. Thats where the conversations are taking place. 

Thank you.
