### ISSUE TITLE
64bit Warning when submitting to Google Play store.

### ISSUE THREAD

**Issue by Alzy** [Jasonette/JASONETTE-Android#260]
Google now gives the following error:

> This release is not compliant with the Google Play 64-bit requirement
> 
> The following APKs or App Bundles are available to 64-bit devices, but they only have 32-bit native code: 5.
> 
> From August 1, 2019 all releases must be compliant with the Google Play 64-bit requirement.

Analyzing the apk, I notice that the culprit seems to be the J2V8 library as it only compiles 32bit .so files. How can I resolve this issue? I have done a lot of work figuring out and building my Jasonette app to have it come to a halt

**Comment by Alzy** [comment]
UPDATE: following [this thread](https://github.com/eclipsesource/J2V8/issues/384), I found the solution. In your build.grade file change 

```
implementation 'com.eclipsesource.j2v8:j2v8:5.0.103@aar'
```
to
```
implementation 'com.eclipsesource.j2v8:j2v8:4.8.4@aar'
```

and it should compile both 32 and 64 bit libraries.

**Comment by clsource** [comment]
thanks!

**Comment by clsource** [comment]
@Alzy I could not find the line you are refering to. Please could you provide the exact place where this needs to be changed?.

Thanks.

**Comment by clsource** [comment]
Maybe is here?

https://github.com/jasonelle/jasonette-android/blob/master/app/build.gradle#L42
