### ISSUE TITLE
Top section of web browser doesn't get taps

### ISSUE THREAD

**Issue by kcorey** [Jasonette/JASONETTE-Android#263]
Hi All,

Ignacio asked me to take a look at this issue:
https://jasonette.slack.com/archives/C2PUV4Z99/p1572273132053100?thread_ts=1563782847.002700&cid=C2PUV4Z99

When I did I noticed that there's a recyclerview that's created to use when the 'items' in the json of the body are defined.  If there are no items as in Ali's script, the recyclerView still takes up a default space, even though it's got nothing in it.

I noticed that where the list of items is set (JasonViewActivity.java:setup_sections():2191) if we hide the listview when the list size is zero, the problem goes away.

I'm a **complete** jasonette newbie, so I don't know if this will cause folks any trouble, and so should be taken with a _huge_ grain of salt.

I forked the repo, and have crated a PR called bug/ZeroItemsBlockFix.  I have tried to create a PR for what seems appropriate branches.  Again, a total newbie here.  I'm not even sure if it can be seen (I can't see it from my PoV.

Feedback gratefully accepted.

-Ken

**Comment by clsource** [comment]
Hello, please make this in the @jasonelle repository. since this repo is not maintained anymore :) thanks.

**Comment by kcorey** [comment]
The pull request made it into jasonelle, but (and perhaps this is a permissions issue), I cannot see an 'issue' tab in jasonelle/jasonette-android.

**Comment by clsource** [comment]
@kcorey yes. all the issues should be put inside https://github.com/jasonelle/jasonelle repo so is easier to track all the components in a single repo :) thanks.
