### ISSUE TITLE
Opacity for components

### ISSUE THREAD

**Issue by gliechtenstein** [Jasonette/JASONETTE-Android#28]
On iOS you can attach the `opacity` attribute to any component's `style` and it would make it translucent. But this has not been implemented on Android.

I haven't dug deeply into this issue so not sure how complicated it would be to add a generic opacity-altering feature for all `JasonComponent` based classes.

**Comment by wajahatch888** [comment]
Opacity is added. Please review [PR](https://github.com/Jasonette/JASONETTE-Android/pull/32)
