### ISSUE TITLE
html component

### ISSUE THREAD

**Issue by gliechtenstein** [Jasonette/JASONETTE-Android#30]
Implement `html` component so we can display the html result parsed from [$convert.rss](https://github.com/Jasonette/JASONETTE-Android/pull/21), etc.

https://jasonette.github.io/documentation/components/#html

**Comment by brad** [comment]
@gliechtenstein I'm working on this one, can you assign this to me please?

**Comment by gliechtenstein** [comment]
@brad can't assign for some reason, but please feel free to send the PR, looking forward to it!

**Comment by gliechtenstein** [comment]
Resolved with https://github.com/Jasonette/JASONETTE-Android/pull/43
