### ISSUE TITLE
map component

### ISSUE THREAD

**Issue by gliechtenstein** [Jasonette/JASONETTE-Android#31]
Implement map component https://jasonette.github.io/documentation/components/#map

**Comment by brad** [comment]
@gliechtenstein I've begun work on this, can you please mark this "In progress"?

**Comment by gliechtenstein** [comment]
@brad just decided to use a `in progress` label as an ad hoc approach, also moved it to "in progress" from the project board!

**Comment by brad** [comment]
Cool, thanks!

**Comment by gliechtenstein** [comment]
DOne, thanks brad! 🥇
