### ISSUE TITLE
POST with a 401 return code seems to "halt" the app with a spinner

### ISSUE THREAD

**Issue by cpg** [Jasonette/JASONETTE-Android#4]
i can provide a url in private to diagnose this

**Comment by gliechtenstein** [comment]
This may have been fixed with https://github.com/Jasonette/JASONETTE-Android/commit/44c8516a56474d38abc2b6f79a8c6687c4659eb3

Please check.

**Comment by cpg** [comment]
This appears to at least not halt the app, so it's a step forward.

However, the current code seems to call the `success` path, not the `error` path.

I can tell because in my app that success path is a "logged in" url following the post instead of a batter. My app triggers a redirect back to a login page, which works out ok, just not as natural as an error `$util.banner`.

**Comment by gliechtenstein** [comment]
ok let me take another stab at this, please ping me on slack to share the url i'll try and try to fix it for the use case

**Comment by gliechtenstein** [comment]
Fixed with https://github.com/Jasonette/JASONETTE-Android/commit/24505ab9f0bcb25bf97fe4e6c95ab8b5a60341e8 ! I saw the banner with my own eyes this time, so it should work!

**Comment by cpg** [comment]
Great job! Works perfectly!
