### ISSUE TITLE
$params.key not reset between each detail view

### ISSUE THREAD

**Issue by cone56** [Jasonette/JASONETTE-Android#63]
Taking the "_iOS Dev Weekly_" example where the `master.json` view transitions to the `detail.json` view

In `master.json`, the parameter `issue` is set:

https://github.com/gliechtenstein/iosdevweekly.json/blob/master/master.json#L41

Then in `detail.json`, `$params.issue` parameter is used for a network request:

https://github.com/gliechtenstein/iosdevweekly.json/blob/master/detail.json#L40

The first transition from master to detail works correctly, but when you go back to the master view and then go to a *different* detail view, the `$params.issue` is still set to the old value - it's not reset - its value is not being overwritten.

I've tried playing around with `$cache.reset`, `$set` and `$get` actions without success

I think the issue may lie around this area: https://github.com/Jasonette/JASONETTE-Android/blob/develop/app/src/main/java/com/jasonette/seed/Core/JasonModel.java#L41

This is not a problem for the iOS project, only Android

Awesome project BTW! 👍

**Comment by gliechtenstein** [comment]
Thanks for reporting! Just fixed it with https://github.com/Jasonette/JASONETTE-Android/commit/9bf7bf6907ee0677e71b75034c7aa5ba07d8a22c

Please try and let me know if it works for you.

**Comment by cone56** [comment]
Works perfectly, thanks for the quick fix!
