### ISSUE TITLE
Implementing example Weather app throws error

### ISSUE THREAD

**Issue by jason07** [Jasonette/JASONETTE-Android#64]
While trying to implement provided weather app example, andriod studio keeps throwing below exception -
Error: java.lang.ClassNotFoundException: com.jasonette.seed.Action.JasonGeoAction

Perhaps a missing file?

![2017-02-15 11_30_30-jasonette-android-master - c__users_jgohil_documents_androidstudio_jasonette-an](https://cloud.githubusercontent.com/assets/4076273/22962337/39e03c4c-f372-11e6-8235-d26c6391f331.jpg)

**Comment by gliechtenstein** [comment]
Sorry about the confusion, there are some actions and components not yet implemented on the Android version, they are all on the todolist. You can check them out here - https://github.com/Jasonette/JASONETTE-Android/projects/1

But basically the goal of the initial release was to get it to a point where you can build

1. a network-connected app
2. that communicate with the server
3. which provides full interactivity with the user and system events

As can be seen on the todo list, there are some features missing, but we will get to them soon. If you can do Android programming, you are welcome to contribute to some of those modules too. Hope this makes sense!
