### ISSUE TITLE
Offline like iOS?

### ISSUE THREAD

**Issue by PandawanFr** [Jasonette/JASONETTE-Android#66]
Apparently, there is an offline feature on iOS which can cache the whole json file so you can still open the app when offline. It would be nice for that feature to be cross platform.

**Comment by NahomAgidew** [comment]
+1

**Comment by carstengrimm** [comment]
+1

**Comment by DanielStevenLewis** [comment]
According to https://github.com/Jasonette/JASONETTE-iOS/issues/48 , there was limited _undocumented_ iOS offline support quite a while back. I'm wondering whether there's similar undocumented functionality for Android.

**Comment by gliechtenstein** [comment]
Added with https://github.com/Jasonette/JASONETTE-Android/commit/34de08724d0824e1d1f5f250b2ffc69e0a80bbba
