### ISSUE TITLE
secure textfields lose style when adding "secure"

### ISSUE THREAD

**Issue by cpg** [Jasonette/JASONETTE-Android#7]
when adding `"secure": "true"` to a text field, it appears that it loses some or all of the style.

will add some sample code later, but it's easy to reproduce. make both fields with a bold font and make one "secure".

**Comment by gliechtenstein** [comment]
Fixed with https://github.com/Jasonette/JASONETTE-Android/commit/9044f913cb4a189cc8557e333f405b3a58649db7 !

**Comment by cpg** [comment]
Worked well. Great job!
