### ISSUE TITLE
camera type background

### ISSUE THREAD

**Issue by gliechtenstein** [Jasonette/JASONETTE-Android#78]
There's a "camera" type background on iOS that's missing on Android: http://docs.jasonette.com/document/#example-4-advanced-camera-background

**Comment by thetomester13** [comment]
+1 for this!

**Comment by realitix** [comment]
@gliechtenstein Can you give a jasonette app example because in the documentation, I only see camera for action but not for background.

**Comment by thetomester13** [comment]
This example makes use of the camera for a background: http://docs.jasonette.com/examples/#weather

**Comment by gliechtenstein** [comment]
@realitix I actually got rid of this from the documentation because it wasn't implemented on Android and people kept complaining about how it doesn't work, and I couldn't find time to work on it. Here's what it used to look like https://github.com/Jasonette/documentation/commit/9ae3d945bd05290f868b0cd0370f2e9d93274927

But I hope to bring this back someday. All we need is the Android counterpart and we can add it back to the documentation. If anyone is interested in taking a stab at it that would be awesome :)

**Comment by realitix** [comment]
Maybe I'm fool enough to do it @gliechtenstein !

**Comment by thetomester13** [comment]
I did some research about this earlier but never officially got around to it. Hopefully this can lead you down the right path! http://stackoverflow.com/a/12733534

**Comment by gliechtenstein** [comment]
> Maybe I'm fool enough to do it @gliechtenstein !

@realitix you would be genius enough to do it 😁

**Comment by realitix** [comment]
@gliechtenstein Can you assign me this issue, I'm working on it.
I face a problem: there are 2 cameras modules, an old one (deprecated) and the new one.
Of course I want to use the new one, but it requires API 21 minimum and Jasonette currently supports API 17...
I don't want to waste time on the deprecated API because API 21 will soon be supported everywhere.
Currently ~20% of devices don't support API 21 (https://developer.android.com/about/dashboards/index.html).

**Comment by gliechtenstein** [comment]
I tried to assign but for some reason the feature is not working. But I think this thread is good enough to discourage anyone else from picking it up while you're working on it :)

One concern I have though:

> Of course I want to use the new one, but it requires API 21 minimum and Jasonette currently supports API 17...
I don't want to waste time on the deprecated API because API 21 will soon be supported everywhere.
Currently ~20% of devices don't support API 21 

Wouldn't this mean the entire Jasonette project's minimum API level needs to be raised to API 21? That would mean 20% of the devices wouldn't be able to run Jasonette and I think that might be too much...

**Comment by realitix** [comment]
Indeed @gliechtenstein 20% is too much people. I'm going with the old API.

**Comment by gliechtenstein** [comment]
Got it! Looking forward to it!

**Comment by realitix** [comment]
You can try the pull request, make it crash ! ...and I will fix it :+1:

**Comment by realitix** [comment]
Done! You can close this issue @gliechtenstein

**Comment by gliechtenstein** [comment]
🙆
