### ISSUE TITLE
Form inputs?

### ISSUE THREAD

**Issue by mattbrailsford** [Jasonette/JASONETTE-Android#80]
I can see in the demo there is a text field / text area and button, but are there any other inputs supported out of the box? such as radio buttons, checkboxes, toggle switches?

**Comment by gliechtenstein** [comment]
We might add those in the future but at the moment think that all of those can be achieved with any of `label`, `button`, `image` components. 

Will revisit this issue later, but for now try writing a template logic that switches on and off the state using local variables, and then re-`$render` every time you touch it.

Hope this makes sense. Let me know if you have more questions

**Comment by mattbrailsford** [comment]
Nope that makes sense and thought that was the case. Was just hoping for a "native" option so I didn't have to style them to look native, but I understand priorities, so no worries.
