### ISSUE TITLE
Mixin for local JSON

### ISSUE THREAD

**Issue by gliechtenstein** [Jasonette/JASONETTE-Android#81]
Just like iOS https://github.com/Jasonette/JASONETTE-iOS/pull/148

**Comment by hoffmabc** [comment]
When do we think this one will be merged? Thanks for the hard work.

**Comment by gliechtenstein** [comment]
I'm trying to finish up something else I've been working on for Jasonette, and planning on finishing it up in a couple of weeks.

Then I'll get back to all the open issues on https://github.com/Jasonette/JASONETTE-Android/projects/1 , where this is one of the top priority issues. I'll update the status here when I get to it!

**Comment by gliechtenstein** [comment]
Fixed with https://github.com/Jasonette/JASONETTE-Android/commit/8aa2566ab4bfaf2fcd657aab633bb9522beb8005

Also see https://github.com/Jasonette/JASONETTE-Android/issues/110 => This update adds local support for both mixins and the $require action
