### ISSUE TITLE
Template doesn't support action within it?

### ISSUE THREAD

**Issue by qwemicheal** [Jasonette/JASONETTE-Android#82]
I followed the doc to use template to load data dynamically from server. Everything works fine. But I encountered the following issue when trying to add action to template:

You can find the complete code on http://45.76.220.41/json/detail_working.json
http://45.76.220.41/json/detail_not_working.json.

Every time I add action to a label within template, Jasonette would stop on the loading circle. Also, the server side log show that Jasonette never made the post request defined in the template action.

The only difference between the working and the not working json file is as following 

              "action": {
                "type": "$network.request",
                "options": {
                  "url": "http://45.76.220.41/test/erase",
                  "method": "post",
                  "data": {
                    "event": "{{event_name}}",
                  },
                  "content_type": "json"
                }
            }

Am I using template wrong or it's because template doesn't support action within it ?

**Comment by gliechtenstein** [comment]
looking at your code, you're using `actions` instead of `action`, first need to fix that.

Also your JSON is not a valid JSON. To make sure this doesn't happen, you can try using http://jsonlint.com/ or just use https://jasonbase.com to host your JSON, which takes care of all the linting for you as well as store them.

**Comment by qwemicheal** [comment]
Thanks for your reply. 
I misunderstood `actions` and `action`. After changing the typo and apply `actions` and `action` correctly. The code is working now.
