### ISSUE TITLE
Issue with html template

### ISSUE THREAD

**Issue by frequeradio** [Jasonette/JASONETTE-Android#85]
Hi

While trying to make the html template works with the exemple of the documentation ( https://www.jasonbase.com/things/5yp.json  ) i have an error at the execution 

03-27 16:28:07.746 7125-7125/com.jasonette W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
03-27 16:28:07.772 7125-7198/com.jasonette E/EGL_emulation: tid 7198: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
03-27 16:28:07.772 7125-7198/com.jasonette W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa7177260, error=EGL_BAD_MATCH
03-27 16:28:07.921 7125-7195/com.jasonette D/Error: org.json.JSONException: No value for $load
03-27 16:28:07.922 7125-7195/com.jasonette D/Error: org.json.JSONException: No value for $show

is it an error with the parsing of the webpage or with jasonette ?

**Comment by gliechtenstein** [comment]
Could you try it on latest develop branch? https://github.com/Jasonette/JASONETTE-Android/archive/develop.zip

I just tried the same URL on mine and it's working fine on mine.

p.s.
Some of the exceptions in the console are actually not errors. sorry for the confusion. As long as it works it's fine.

**Comment by frequeradio** [comment]
Works perfect with the last branch and last update of Android :)

**Comment by gliechtenstein** [comment]
Closing this, but before I do, just want to mention that HTML component has been vastly upgraded and the syntax has changed a bit. Check it out here http://docs.jasonette.com/web/
