### ISSUE TITLE
examples not working on my Android 5.1.1 (API 22)

### ISSUE THREAD

**Issue by j2l** [Jasonette/JASONETTE-Android#87]
I tested all examples from http://docs.jasonette.com/examples/
I only get eliza first sentence, no reply block or keyboard. All the rest is spinning loading wheel forever (we've got a 1GB internet on fiber optics, not a network issue).
I also get no "GO" button in Jason app on Google Play

**Comment by carstengrimm** [comment]
maybe share your json file?
did you try to access the file yourself in a browser to see if there is any errors? 
Just tried and compiled from latest dev branch and my json is working on 5.1. like a charm

**Comment by j2l** [comment]
Examples don't work, I have nothing to share.
Yes, I tested examples in a browser.
Not tried dev branch though. Well issue might be fixed in master soon I guess.

**Comment by j2l** [comment]
The one I reported was master link published at http://docs.jasonette.com/android/

Tested dev branch:
        targetSdkVersion 25 on API25 emulator => Works OK
        targetSdkVersion 22 => Package com.jasonette new target SDK 22 doesn't support runtime permissions ...
        targetSdkVersion 23 on API23 emulator => Works OK

**Comment by j2l** [comment]
targetSdkVersion 23 on API22 emulator => Works OK!
 targetSdkVersion 23 on API22 phone => Works OK!
So it was both "dev vs master" and targetSdkVersion
