### ISSUE TITLE
AddressBook Permissions Android API 23

### ISSUE THREAD

**Issue by j2l** [Jasonette/JASONETTE-Android#88]
Testing AddressBook, 
Works fine in API 22.
But in API 23 (& 25), even after commenting out to get:
    <uses-permission android:name="android.permission.READ_CONTACTS" />
in AndroidManifest.xml

it throws:
$util.addressbook requires additional permissions.
![image](https://cloud.githubusercontent.com/assets/65325/24554027/77ddd860-162c-11e7-8323-75ecfa0c5575.png)

**Comment by gliechtenstein** [comment]
On Android you need to turn it on explicitly. Please try this and let me know if that works, then I'll close it http://docs.jasonette.com/actions/#required-permissions

**Comment by j2l** [comment]
Hi, 
That's exactly what I did.

Sorry, my sentence wasn't clear, some copy paste was missing:
"But in API 23 (& 25), even after commenting out to get:
android.permission.READ_CONTACTS
in AndroidManifest.xml"

So it's broken for me so far.

**Comment by j2l** [comment]
I found this one by myself:
The app is not showing the Android Permission ("Contacts") warning so you can enable it directly (why?). 
You need to MANUALLY go into App info > Permission > Contacts=enabled.
THEN it will work.
Closed
